### ISSUE TITLE
Incorrect temperature readings below zero (IT+/WS1600)

### ISSUE THREAD

**Issue by aj-gh** [rinie/weatherstationFSK#3]
It should be noted that both in the IT+ code and in the WS1600 code the temperature calculations return incorrect readings when the measured temperature is below zero.
This is related to the way how the digits are split into temp and tempDeci. In the protocol itself the value contains both parts and needs to be reduced by 400 which is not the same as stripping the last digit and reducing the remaining value by 40 instead - that only returns correct results for temperatures >0.
I suppose a possible fix would be to calculate it as a floating point number, similar to what is being done for TX38IT in the FEHM project code.

**Comment by rinie** [comment]
Fixed by 			    frame->Temperature = ((temp * 10 + tempDeci) - 400) / 10;
